### ISSUE TITLE
Sending multiple request at the same time,some of then are not detected by the server

### ISSUE THREAD

**Issue by nexhero** [holepunchto/bare-http1#20]
https://github.com/holepunchto/bare-http1/blob/ac51debc269538518d445625660cca1a7999ba49/lib/server.js#L13

**Comment by nexhero** [comment]
example
![http](https://github.com/user-attachments/assets/2de430c7-0f51-4b9f-ba18-8b8ed163e5fb)

**Comment by mafintosh** [comment]
Can you provide more details, and also a test case so we can fix?

**Comment by nexhero** [comment]
I'm unable to replicate the error , I'm debugging my project to figure out, I only know that after changing the timeout all work

**Comment by nexhero** [comment]
after review my code, I found out that I was using http1 v3.8.2, before the bare-tcp update, I upgrade http1 v4 and works

**Comment by nexhero** [comment]
after review my code, I found out that I was using http1 v3.8.2, before the bare-tcp update, I upgrade http1 v4 and works

**Comment by mafintosh** [comment]
Awesome
